FROM ubuntu:22.04

ENV AWS_ACCESS_KEY_ID="AKIA123456788"
ENV AWS_SECRET_ACCESS_KEY="secret123456789"
ENV DATABASE_PASSWORD="admin123"

COPY . /app

WORKDIR /app

RUN apt-get update
RUN apt-get install -y curl wget

CMD ["python3", "app.py"]