FROM ubuntu:22.04

ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""
ENV DATABASE_PASSWORD=""

COPY . /app

WORKDIR /app

RUN apt-get update
RUN apt-get install -y curl wget

CMD ["python3", "app.py"]