FROM ubuntu:latest

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip3 install flask

ENV SECRET_KEY="my-super-secret-key"

USER root

EXPOSE 5000

CMD ["python3", "app.py"]